CREATE TABLE IF NOT EXISTS org_nodes (
  id integer PRIMARY KEY,
  name varchar(200) NOT NULL,
  level integer NOT NULL,
  "parentId" integer NULL REFERENCES org_nodes(id) ON DELETE SET NULL,
  path text NULL
);

CREATE INDEX IF NOT EXISTS idx_org_nodes_parent_id ON org_nodes ("parentId");
CREATE INDEX IF NOT EXISTS idx_org_nodes_path ON org_nodes (path);

CREATE TABLE IF NOT EXISTS users (
  id integer PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  "passwordHash" varchar(255) NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS facilities (
  id integer PRIMARY KEY,
  name varchar(200) NOT NULL,
  code varchar(50) NULL,
  "orgNodeId" integer NOT NULL REFERENCES org_nodes(id) ON DELETE CASCADE,
  "isActive" boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_facilities_org_node_id ON facilities ("orgNodeId");

CREATE TABLE IF NOT EXISTS user_permissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "orgNodeId" integer NOT NULL REFERENCES org_nodes(id) ON DELETE CASCADE,
  "orgNodeLevel" integer NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_user_permissions_user_id ON user_permissions ("userId");
CREATE INDEX IF NOT EXISTS idx_user_permissions_org_node_id ON user_permissions ("orgNodeId");

CREATE TABLE IF NOT EXISTS pulse_responses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "facilityId" integer NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  score integer NOT NULL,
  category varchar(100) NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pulse_responses_facility_id ON pulse_responses ("facilityId");
CREATE INDEX IF NOT EXISTS idx_pulse_responses_created_at ON pulse_responses ("createdAt");

CREATE TABLE IF NOT EXISTS survey_responses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "facilityId" integer NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  "surveyType" varchar(100) NOT NULL,
  answers jsonb NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_survey_responses_facility_id ON survey_responses ("facilityId");
CREATE INDEX IF NOT EXISTS idx_survey_responses_created_at ON survey_responses ("createdAt");

TRUNCATE TABLE
  survey_responses,
  pulse_responses,
  user_permissions,
  facilities,
  users,
  org_nodes
RESTART IDENTITY CASCADE;

INSERT INTO org_nodes (id, name, level, "parentId", path) VALUES
  (1, 'Acme Corp', 0, NULL, '1'),
  (2, 'West Region', 1, 1, '1.2'),
  (3, 'North Area', 2, 2, '1.2.3'),
  (4, 'Downtown District', 3, 3, '1.2.3.4'),
  (5, 'Main Campus', 4, 4, '1.2.3.4.5'),
  (6, 'East Region', 1, 1, '1.6'),
  (7, 'East Area', 2, 6, '1.6.7');

INSERT INTO facilities (id, name, code, "orgNodeId", "isActive") VALUES
  (10, 'Sunset Clinic', 'SC-01', 3, true),
  (11, 'Riverside Clinic', 'RC-01', 3, true),
  (12, 'Downtown Clinic', 'DC-01', 4, true),
  (13, 'Main Campus Health', 'MCH-01', 5, true),
  (14, 'East Medical Center', 'EMC-01', 7, true);

INSERT INTO users (id, email, "passwordHash", "isActive") VALUES
  (1, 'admin@totale.com', '$2b$04$z1WGGx/8JDeoVQ77QAb0H.AToxfaeyoe7LXkDm2dKk9b/0gSibgDO', true),
  (2, 'region-west@totale.com', '$2b$04$z1WGGx/8JDeoVQ77QAb0H.AToxfaeyoe7LXkDm2dKk9b/0gSibgDO', true),
  (3, 'area-north@totale.com', '$2b$04$z1WGGx/8JDeoVQ77QAb0H.AToxfaeyoe7LXkDm2dKk9b/0gSibgDO', true),
  (4, 'district@totale.com', '$2b$04$z1WGGx/8JDeoVQ77QAb0H.AToxfaeyoe7LXkDm2dKk9b/0gSibgDO', true),
  (5, 'campus@totale.com', '$2b$04$z1WGGx/8JDeoVQ77QAb0H.AToxfaeyoe7LXkDm2dKk9b/0gSibgDO', true),
  (6, 'region-east@totale.com', '$2b$04$z1WGGx/8JDeoVQ77QAb0H.AToxfaeyoe7LXkDm2dKk9b/0gSibgDO', true);

INSERT INTO user_permissions ("userId", "orgNodeId", "orgNodeLevel", "isActive") VALUES
  (1, 1, 0, true),
  (2, 2, 1, true),
  (3, 3, 2, true),
  (4, 4, 3, true),
  (5, 5, 4, true),
  (6, 6, 1, true);

INSERT INTO pulse_responses ("facilityId", score, category, "createdAt") VALUES
  (10, 8, 'Engagement', NOW() - INTERVAL '6 days'),
  (10, 6, 'Wellbeing', NOW() - INTERVAL '5 days'),
  (10, 9, 'Engagement', NOW() - INTERVAL '3 days'),
  (11, 7, 'Safety', NOW() - INTERVAL '5 days'),
  (11, 5, 'Wellbeing', NOW() - INTERVAL '2 days'),
  (11, 8, 'Safety', NOW() - INTERVAL '1 day'),
  (12, 7, 'Engagement', NOW() - INTERVAL '4 days'),
  (12, 5, 'Safety', NOW() - INTERVAL '3 days'),
  (13, 9, 'Wellbeing', NOW() - INTERVAL '5 days'),
  (13, 8, 'Engagement', NOW() - INTERVAL '2 days'),
  (14, 6, 'Safety', NOW() - INTERVAL '3 days'),
  (14, 7, 'Wellbeing', NOW() - INTERVAL '1 day');

INSERT INTO survey_responses ("facilityId", "surveyType", answers, "createdAt") VALUES
  (10, 'annual', '{"q1":"yes","q2":"somewhat"}'::jsonb, NOW() - INTERVAL '6 days'),
  (10, 'quarterly', '{"q1":"no"}'::jsonb, NOW() - INTERVAL '2 days'),
  (11, 'annual', '{"q1":"yes"}'::jsonb, NOW() - INTERVAL '4 days'),
  (11, 'quarterly', '{"q1":"yes","q2":"very"}'::jsonb, NOW() - INTERVAL '1 day'),
  (12, 'annual', '{"q1":"yes"}'::jsonb, NOW() - INTERVAL '4 days'),
  (13, 'quarterly', '{"q1":"yes","q2":"very"}'::jsonb, NOW() - INTERVAL '3 days'),
  (14, 'annual', '{"q1":"no","q2":"somewhat"}'::jsonb, NOW() - INTERVAL '2 days');
